sudo: true
dist: trusty
env:
  global:
  - IMAGE_NAME="umccr/crypt4gh"
  - DOCKER_USERNAME="umccrsvc"
  - secure: c/OfwRI69N9tiq3Qtn3vAg4Z74zIMh18cs6JuvZAhzv3Gfghq7WDy5Rt9hV6zNNJyYA229UrYx/EprSSyS5j8OnqeON2s74Tzahggy2tyVoIh0pJ3q6g6Yr+eh9iBg+8v8Xubnxqu6fM0plLDjZc+OVdRuc0gJWhz0W93cgJZIOakNRJG1QHNgYXA9HHa24EDHc2ERtiBeST5JcrSKwPEKqiauDvsOJbF77mLhfteAk/fM/q1EJ5NdeNhHTQy8SuiCjGfwShbvj0JtePonSHAy4sjMBP7fbssWInQi41eQAzaR6frfLcqlLwyArmXrGjfxM4v5Gkp4jWewnUTyiq+MvTI5RDDTCI36Fh5pEot1RrS85ys7O1rIqnyBn0jhqNnCSBq7EP97X/hXEA0oztgEVNnmxSD9cVrBBWgKBuEjgCFlfQSCaXqutUoa6ty1rrfZxqsyNiIZzYhvoyl0WDUX30xQGcuFI+8Aq2ay5APJkoDMxmfSD03IEtFFjcd9mIG+fD+w+HD5H5zlKXoXYKr3BIRX/0YsfJqsidWqMVWWIcCdQoJIacILCgYYa/jODl6CE5KxSqPWojA8ULdBRbAivpOE38/1aNRCctFbNduhGSYwI21PNNkBhsdRNodgXKNL4CbjPPzdCeiwliDm6sl1cvyV3rYPx2vRn1SiEMrPM=
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME:$TRAVIS_BUILD_NUMBER .
    - docker tag $IMAGE_NAME:$TRAVIS_BUILD_NUMBER wandergeek/telotest:latest
    - docker images
    - docker push $IMAGE_NAME:${TRAVIS_BUILD_NUMBER}
    - docker push $IMAGE_NAME:latest
