sudo: true
dist: trusty
env:
  global:
    - secure: QU37hmi0zBwCCwXllRWinh3p2r1THcEbzoJHNvDqpgN2C8IY3UCT0M/zYTpZk2DTTmSrx7Q4hkIxdwz+ZpgWiDWErYRjNe5sYUfl+97aCkH43uDvUwoAG+t1RghOqXuWrV9ztm12mmvogECL3dr50N0i+osHDhufgvES9BFyiz1Z1NKfRqDIZEUo4lZMXCqBMFcRZSM4vu7s131F1MExBrHJpEHYf1eurpM8esvRp3Bk3MmOzdqipKcdqspVG+wWmFMu8WVSlDcfRF1qQdh4nVQT5NM5saDm+MPxWhyBerfMkW4WXU3QOG2JClC48/kyN7OL2EDYO2jcd1P8UHHHACD4QwifPn2Lv2tpjb/mECVExyRSqJ2IR+An6kUhhhOq5KsWBuJXoG6UPrSJflStJ3Adn6QmuyX8jabgQ9l7dKYg0R5gL8rFpw1f8QBluEeAcx6yE+wuMmqtrTl3rssyJHLDKaX8DzUGKfr37ipCsG6YTMM2dNA8nT/6nNckP1Jwn4yyFM2DCAgMCmVfRlH9C+AZmN5EykkfG5cTFzrm96Rw2wjHJd5rICUXOoMMAvqepqlKbeSYlrx6FPkUFXaqVGOep/HCOjiH1jX4HNXVp66kjwbfBYcAzPrhfEbM8OBZmCyOWHOBMoOGmwrktJqAE0ITSAvIJTrKRlUT/BInYCA=
    - IMAGE_NAME="umccr/crypt4gh"
    - DOCKER_USERNAME="umccrsvc"
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME:$TRAVIS_BUILD_NUMBER .
    - docker tag $IMAGE_NAME:$TRAVIS_BUILD_NUMBER wandergeek/telotest:latest
    - docker images
    - docker push $IMAGE_NAME:${TRAVIS_BUILD_NUMBER}
    - docker push $IMAGE_NAME:latest