sudo: true
dist: trusty
env:
  global:
  - IMAGE_NAME="umccr/crypt4gh"
  - DOCKER_USERNAME="umccrsvc"
  - secure: JUSsRCKc+atw2sOCX6xktwoFcEdmSWma/owgcB9O0EPonHfGXXDspDuhB09FZnUP3H0SV+z+IMkUOuHt9V8G9aZ08nYEjysUTOmdt90cNn6euwJwjeKkiW4VtNFhpM/4m0oVz+oOUfZALkLEOoBD79az/iEi//RLCx+FjRLr/9LfV9Ss7XcbCStchkyUI0FJ/giA7d5excq/7uOIMgmGpgb6Qc2WMgsbG/yrZu65hVfKXdciJMDFSHVgZ5UZT/CIzzWa6EdcKE0yBBjdARBfyuLe7vEtlSehPXEZf7LHjv4RUfpFpKGf0n9Srgn+QnufLYBxIT+/Dk7mLKvObu+ABz9r4tVnrphm7HDSiPEu7RhMawm/KUVg6hrbOi8DArxLZjQQy7NxfJBClPF5QwnNuou/tHKOqxeDZPFKaHD+A8+ndRwx0TUiXCGOJ7eo4jdi7BJODQU01oR2MhNoXM0/egLrIYeBHCSE62/P4zPOm9Z4QjaIUlvxdXklL+munwyURZQvkeT/0CXouWnU5OuNnj6Cm6kNxtiwsVfI9rnRGsh7pZ79b02CACpSqVaPJnyJlMbNWSbtRl6NyIEVUXP91TLZN/U0FWe7PUUIdITSePO/TDYhvWaljRs5Y+UDTvxPrLaCjkD6+hvhIf9MQqOFkHiJiMvryYcWfBndZPuMsi8=
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME:$TRAVIS_BUILD_NUMBER .
    - docker tag $IMAGE_NAME:$TRAVIS_BUILD_NUMBER wandergeek/telotest:latest
    - docker images
    - docker push $IMAGE_NAME:${TRAVIS_BUILD_NUMBER}
    - docker push $IMAGE_NAME:latest
